/*******************************************************************************
a) Register a new user
b) Subscribe a user to an app
c) Add a show to a user’s “My List”
d) Update an app’s version on a platform
e) Add a new video (with all associated meta data), which is the latest in a show’s current season
f) Produce a ranked list of the top-10 most watched shows, each with the corresponding app
g) Find all free videos on a particular platform
h) Find all long videos that were released this year and aren’t part of any show
i) Produce a ranked list of revenue generated by apps in a country
j) Produce a ranked list of watch counts from the top-3 video tags
********************************************************************************/
/* a) */
INSERT INTO [User] VALUES (11,'j.m@gmail.com','Jess','M','USA','19970sdf04');

/* b) */
INSERT INTO [Subscription] VALUES (10, 'Youtube', 4, '2024-07-18 00:00:00');

/* c) */
INSERT INTO [MyList] VALUES (10, 10);
INSERT INTO [MyShow] VALUES (10, 1);

/* d) */
UPDATE [AppPlatform] set [Version] = 10.7 where [AppName] = 'Youtube' AND [Platform] = 'Android';

/* e) */
INSERT INTO [Video] ([id], [Title], [Description],[ReleaseDate],[Duration],[subscribe]) Values (11,'breakfast cooking','learn three ways to cook egg', '2020-11-15 00:00:00',160, false);

/* f) */
select a.Title,
(
select sh.Title,v.AppName,count(*) as Views
from ((Show sh inner join Video v on sh.Id = v.ShowId)
inner join UserVideo uv on v.Id = uv.VideoId)
inner join User u on uv.UserId = u.Id
group by v.ShowId
order by Views
) a

/* g) */
/* Find all free videos on a particular platform
    Platform is parameterized, currently shown with the value of 'Android'
*/
select v.Id as Video
from (Video v inner join App a on v.AppName = App.Name)
inner join AppPlatform ap on a.Name = ap.AppName
where v.Subscribe = false and ap.Platform = 'Android'

/* i) */
/* Produce a ranked list of revenue generated by apps in a country
    Country is parameterized, currently shown with the value of 'China'
*/
select s.AppName as app, sum(s.Cost) as revenue
from User u.Id inner join Subscription s on u.Id = s.UserId
group by s.AppName
where u.Country = 'China'
order by revenue

/* j)  
Produce a ranked list of watch counts from the top-3 video tags */
Select TOP count(vt.Tag)
From Video v
join VideoTags vt on v.AppName = vt.VideoApp



